services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=my_lab
      - POSTGRES_USER=fabi
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root123
    ports:
      - 5050:80


